spring:
  config:
    import: optional:secrets.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
              ${googleClientId.key}
            client-secret:
              ${googleClientSecret.key}
          facebook:
            client-id:
              ${facebookClientId.key}
            client-secret:
              ${facebookClientSecret.key}
            scope:
              - email
              - public_profile





  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #  change localhost with database-container to use it in docker
#    change DB
    url: "jdbc:mysql://localhost:3306/travel_mate?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: root
    password: 125963Denis

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#mail:
#  # raplace localhost with my-mailhog   mailhog container name
#  host: "localhost"
#  port: 1025
#  username: "hike@addict.com"
#  password: ""

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - prometheus



